### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by SamWilsn**

### CODE REVIEW

**Comment by lightclient** [comment]
do we really need issue templates? :(

**Comment by SamWilsn** [comment]
No, I don't think we need them, but I think they're kinda neat. I can remove them if you like.

**Comment by voith** [comment]
I think it's good to have at least some kind of issue template. My reasons:
- Helps define clear goals.
- Following a format makes sure that necessary details are included. This becomes very helpful when a ticket has been left untouched for a long period. The context behind the ticket can easily be forgotten.
- If a ticket has "sufficient" details, it becomes easy for external contributors(like myself) to contribute without much friction.
- It's a reminder for a lazy person(like myself) to follow the format so that the ticket serves the above-mentioned goals.

**Review by voith — APPROVED** [review]
I really like these templates. Perhaps we could another issue template for feature requests. That can be done in a separate PR.

**Comment by lightclient** [comment]
Okay, I don't mind too much so if you both prefer we can go ahead and use them :)

**Review by lightclient — APPROVED** [review]

**Pull request merged**
